export enum DeviceSettingsActionTypes {
  SET_VIDEO_CAMERA = 'SET_VIDEO_CAMERA',
  SET_VIDEO_INPUT_AUDIO = 'SET_VIDEO_INPUT_AUDIO',
  SET_VIDEO_RESOLUTION = 'SET_VIDEO_RESOLUTION',
  SET_VIDEO_FREQUENCY = 'SET_VIDEO_FREQUENCY',
  SET_VIDEO_MUTED = 'SET_VIDEO_MUTED',
  SET_SCREEN_NUMBER = 'SET_SCREEN_NUMBER',
  SET_SCREEN_RESOLUTION = 'SET_SCREEN_RESOLUTION',
  SET_SCREEN_FREQUENCY = 'SET_SCREEN_FREQUENCY'
}
