import { DefaultItem } from '@consta/uikit/Select'

const citizenships: DefaultItem[] = [
  { id: 'ABH', label: 'Абхазия' },
  { id: 'AUS', label: 'Австралия' },
  { id: 'AUT', label: 'Австрия' },
  { id: 'AZE', label: 'Азербайджан' },
  { id: 'ALB', label: 'Албания' },
  { id: 'DZA', label: 'Алжир' },
  { id: 'ASM', label: 'Американское Самоа' },
  { id: 'AIA', label: 'Ангилья' },
  { id: 'AGO', label: 'Ангола' },
  { id: 'AND', label: 'Андорра' },
  { id: 'ATA', label: 'Антарктида' },
  { id: 'ATG', label: 'Антигуа и Барбуда' },
  { id: 'ARG', label: 'Аргентина' },
  { id: 'ARM', label: 'Армения' },
  { id: 'ABW', label: 'Аруба' },
  { id: 'AFG', label: 'Афганистан' },
  { id: 'BHS', label: 'Багамы' },
  { id: 'BGD', label: 'Бангладеш' },
  { id: 'BRB', label: 'Барбадос' },
  { id: 'BHR', label: 'Бахрейн' },
  { id: 'BLR', label: 'Беларусь' },
  { id: 'BLZ', label: 'Белиз' },
  { id: 'BEL', label: 'Бельгия' },
  { id: 'BEN', label: 'Бенин' },
  { id: 'BMU', label: 'Бермуды' },
  { id: 'BGR', label: 'Болгария' },
  { id: 'BOL', label: 'Боливия' },
  { id: 'BES', label: 'Бонайре, Саба и Синт-Эстатиус' },
  { id: 'BIH', label: 'Босния и Герцеговина' },
  { id: 'BWA', label: 'Ботсвана' },
  { id: 'BRA', label: 'Бразилия' },
  { id: 'IOT', label: 'Британская территория в Индийском океане' },
  { id: 'BRN', label: 'Бруней-Даруссалам' },
  { id: 'BFA', label: 'Буркина-Фасо' },
  { id: 'BDI', label: 'Бурунди' },
  { id: 'BTN', label: 'Бутан' },
  { id: 'VUT', label: 'Вануату' },
  { id: 'HUN', label: 'Венгрия' },
  { id: 'VEN', label: 'Венесуэла Боливарианская Республика' },
  { id: 'VGB', label: 'Виргинские острова, Британские' },
  { id: 'VIR', label: 'Виргинские острова, США' },
  { id: 'VNM', label: 'Вьетнам' },
  { id: 'GAB', label: 'Габон' },
  { id: 'HTI', label: 'Гаити' },
  { id: 'GUY', label: 'Гайана' },
  { id: 'GMB', label: 'Гамбия' },
  { id: 'GHA', label: 'Гана' },
  { id: 'GLP', label: 'Гваделупа' },
  { id: 'GTM', label: 'Гватемала' },
  { id: 'GIN', label: 'Гвинея' },
  { id: 'GNB', label: 'Гвинея-Бисау' },
  { id: 'DEU', label: 'Германия' },
  { id: 'GGY', label: 'Гернси' },
  { id: 'GIB', label: 'Гибралтар' },
  { id: 'HND', label: 'Гондурас' },
  { id: 'HKG', label: 'Гонконг' },
  { id: 'GRD', label: 'Гренада' },
  { id: 'GRL', label: 'Гренландия' },
  { id: 'GRC', label: 'Греция' },
  { id: 'GEO', label: 'Грузия' },
  { id: 'GUM', label: 'Гуам' },
  { id: 'DNK', label: 'Дания' },
  { id: 'JEY', label: 'Джерси' },
  { id: 'DJI', label: 'Джибути' },
  { id: 'DMA', label: 'Доминика' },
  { id: 'DOM', label: 'Доминиканская Республика' },
  { id: 'EGY', label: 'Египет' },
  { id: 'ZMB', label: 'Замбия' },
  { id: 'ESH', label: 'Западная Сахара' },
  { id: 'ZWE', label: 'Зимбабве' },
  { id: 'ISR', label: 'Израиль' },
  { id: 'IND', label: 'Индия' },
  { id: 'IDN', label: 'Индонезия' },
  { id: 'JOR', label: 'Иордания' },
  { id: 'IRQ', label: 'Ирак' },
  { id: 'IRN', label: 'Иран' },
  { id: 'IRL', label: 'Ирландия' },
  { id: 'ISL', label: 'Исландия' },
  { id: 'ESP', label: 'Испания' },
  { id: 'ITA', label: 'Италия' },
  { id: 'YEM', label: 'Йемен' },
  { id: 'CPV', label: 'Кабо-Верде' },
  { id: 'KAZ', label: 'Казахстан' },
  { id: 'KHM', label: 'Камбоджа' },
  { id: 'CMR', label: 'Камерун' },
  { id: 'CAN', label: 'Канада' },
  { id: 'QAT', label: 'Катар' },
  { id: 'KEN', label: 'Кения' },
  { id: 'CYP', label: 'Кипр' },
  { id: 'KGZ', label: 'Киргизия' },
  { id: 'KIR', label: 'Кирибати' },
  { id: 'CHN', label: 'Китай' },
  { id: 'CCK', label: 'Кокосовые (Килинг) острова' },
  { id: 'COL', label: 'Колумбия' },
  { id: 'COM', label: 'Коморы' },
  { id: 'COG', label: 'Конго' },
  { id: 'COD', label: 'Демократическая Республика Конго' },
  { id: 'PRK', label: 'Корея, Народно-Демократическая Республика' },
  { id: 'KOR', label: 'Корея, Республика' },
  { id: 'CRI', label: 'Коста-Рика' },
  { id: 'CIV', label: 'Кот д"Ивуар' },
  { id: 'CUB', label: 'Куба' },
  { id: 'KWT', label: 'Кувейт' },
  { id: 'CUW', label: 'Кюрасао' },
  { id: 'LAO', label: 'Лаос' },
  { id: 'LVA', label: 'Латвия' },
  { id: 'LSO', label: 'Лесото' },
  { id: 'LBN', label: 'Ливан' },
  { id: 'LBY', label: 'Ливийская Арабская Джамахирия' },
  { id: 'LBR', label: 'Либерия' },
  { id: 'LIE', label: 'Лихтенштейн' },
  { id: 'LTU', label: 'Литва' },
  { id: 'LUX', label: 'Люксембург' },
  { id: 'MUS', label: 'Маврикий' },
  { id: 'MRT', label: 'Мавритания' },
  { id: 'MDG', label: 'Мадагаскар' },
  { id: 'MYT', label: 'Майотта' },
  { id: 'MAC', label: 'Макао' },
  { id: 'MWI', label: 'Малави' },
  { id: 'MYS', label: 'Малайзия' },
  { id: 'MLI', label: 'Мали' },
  { id: 'UMI', label: 'Малые Тихоокеанские отдаленные острова Соединенных Штатов' },
  { id: 'MDV', label: 'Мальдивы' },
  { id: 'MLT', label: 'Мальта' },
  { id: 'MAR', label: 'Марокко' },
  { id: 'MTQ', label: 'Мартиника' },
  { id: 'MHL', label: 'Маршалловы острова' },
  { id: 'MEX', label: 'Мексика' },
  { id: 'FSM', label: 'Микронезия' },
  { id: 'MOZ', label: 'Мозамбик' },
  { id: 'MDA', label: 'Молдова, Республика' },
  { id: 'MCO', label: 'Монако' },
  { id: 'MNG', label: 'Монголия' },
  { id: 'MSR', label: 'Монтсеррат' },
  { id: 'MMR', label: 'Мьянма' },
  { id: 'NAM', label: 'Намибия' },
  { id: 'NRU', label: 'Науру' },
  { id: 'NPL', label: 'Непал' },
  { id: 'NER', label: 'Нигер' },
  { id: 'NGA', label: 'Нигерия' },
  { id: 'NLD', label: 'Нидерланды' },
  { id: 'NIC', label: 'Никарагуа' },
  { id: 'NIU', label: 'Ниуэ' },
  { id: 'NZL', label: 'Новая Зеландия' },
  { id: 'NCL', label: 'Новая Каледония' },
  { id: 'NOR', label: 'Норвегия' },
  { id: 'ARE', label: 'Объединенные Арабские Эмираты' },
  { id: 'OMN', label: 'Оман' },
  { id: 'BVT', label: 'Остров Буве' },
  { id: 'IMN', label: 'Остров Мэн' },
  { id: 'NFK', label: 'Остров Норфолк' },
  { id: 'CXR', label: 'Остров Рождества' },
  { id: 'HMD', label: 'Остров Херд и острова Макдональд' },
  { id: 'CYM', label: 'Острова Кайман' },
  { id: 'COK', label: 'Острова Кука' },
  { id: 'TCA', label: 'Острова Теркс и Кайкос' },
  { id: 'PAK', label: 'Пакистан' },
  { id: 'PLW', label: 'Палау' },
  { id: 'PSE', label: 'Палестинская территория, оккупированная' },
  { id: 'PAN', label: 'Панама' },
  { id: 'VAT', label: 'Папский Престол (Государство — город Ватикан)' },
  { id: 'PNG', label: 'Папуа-Новая Гвинея' },
  { id: 'PRY', label: 'Парагвай' },
  { id: 'PER', label: 'Перу' },
  { id: 'PCN', label: 'Питкерн' },
  { id: 'POL', label: 'Польша' },
  { id: 'PRT', label: 'Португалия' },
  { id: 'PRI', label: 'Пуэрто-Рико' },
  { id: 'MKD', label: 'Республика Македония' },
  { id: 'REU', label: 'Реюньон' },
  { id: 'RUS', label: 'Россия' },
  { id: 'RWA', label: 'Руанда' },
  { id: 'ROU', label: 'Румыния' },
  { id: 'WSM', label: 'Самоа' },
  { id: 'SMR', label: 'Сан-Марино' },
  { id: 'STP', label: 'Сан-Томе и Принсипи' },
  { id: 'SAU', label: 'Саудовская Аравия' },
  { id: 'SWZ', label: 'Свазиленд' },
  { id: 'SHN', label: 'Святая Елена, Остров вознесения, Тристан-да-Кунья' },
  { id: 'MNP', label: 'Северные Марианские острова' },
  { id: 'BLM', label: 'Сен-Бартельми' },
  { id: 'MAF', label: 'Сен-Мартен' },
  { id: 'SEN', label: 'Сенегал' },
  { id: 'VCT', label: 'Сент-Винсент и Гренадины' },
  { id: 'KNA', label: 'Сент-Китс и Невис' },
  { id: 'LCA', label: 'Сент-Люсия' },
  { id: 'SPM', label: 'Сент-Пьер и Микелон' },
  { id: 'SRB', label: 'Сербия' },
  { id: 'SYC', label: 'Сейшелы' },
  { id: 'SGP', label: 'Сингапур' },
  { id: 'SXM', label: 'Синт-Мартен' },
  { id: 'SYR', label: 'Сирийская Арабская Республика' },
  { id: 'SVK', label: 'Словакия' },
  { id: 'SVN', label: 'Словения' },
  { id: 'GBR', label: 'Соединенное Королевство' },
  { id: 'USA', label: 'Соединенные Штаты' },
  { id: 'SLB', label: 'Соломоновы острова' },
  { id: 'SOM', label: 'Сомали' },
  { id: 'SDN', label: 'Судан' },
  { id: 'SUR', label: 'Суринам' },
  { id: 'SLE', label: 'Сьерра-Леоне' },
  { id: 'TJK', label: 'Таджикистан' },
  { id: 'THA', label: 'Таиланд' },
  { id: 'TWN', label: 'Тайвань (Китай)' },
  { id: 'TZA', label: 'Танзания, Объединенная Республика' },
  { id: 'TLS', label: 'Тимор-Лесте' },
  { id: 'TGO', label: 'Того' },
  { id: 'TKL', label: 'Токелау' },
  { id: 'TON', label: 'Тонга' },
  { id: 'TTO', label: 'Тринидад и Тобаго' },
  { id: 'TUV', label: 'Тувалу' },
  { id: 'TUN', label: 'Тунис' },
  { id: 'TKM', label: 'Туркмения' },
  { id: 'TUR', label: 'Турция' },
  { id: 'UGA', label: 'Уганда' },
  { id: 'UZB', label: 'Узбекистан' },
  { id: 'UKR', label: 'Украина' },
  { id: 'WLF', label: 'Уоллис и Футуна' },
  { id: 'URY', label: 'Уругвай' },
  { id: 'FRO', label: 'Фарерские острова' },
  { id: 'FJI', label: 'Фиджи' },
  { id: 'PHL', label: 'Филиппины' },
  { id: 'FIN', label: 'Финляндия' },
  { id: 'FLK', label: 'Фолклендские острова (Мальвинские)' },
  { id: 'FRA', label: 'Франция' },
  { id: 'GUF', label: 'Французская Гвиана' },
  { id: 'PYF', label: 'Французская Полинезия' },
  { id: 'ATF', label: 'Французские Южные территории' },
  { id: 'HRV', label: 'Хорватия' },
  { id: 'CAF', label: 'Центрально-Африканская Республика' },
  { id: 'TCD', label: 'Чад' },
  { id: 'MNE', label: 'Черногория' },
  { id: 'CZE', label: 'Чешская Республика' },
  { id: 'CHL', label: 'Чили' },
  { id: 'CHE', label: 'Швейцария' },
  { id: 'SWE', label: 'Швеция' },
  { id: 'SJM', label: 'Шпицберген и Ян Майен' },
  { id: 'LKA', label: 'Шри-Ланка' },
  { id: 'ECU', label: 'Эквадор' },
  { id: 'GNQ', label: 'Экваториальная Гвинея' },
  { id: 'ALA', label: 'Эландские острова' },
  { id: 'SLV', label: 'Эль-Сальвадор' },
  { id: 'ERI', label: 'Эритрея' },
  { id: 'EST', label: 'Эстония' },
  { id: 'ETH', label: 'Эфиопия' },
  { id: 'ZAF', label: 'Южная Африка' },
  { id: 'SGS', label: 'Южная Джорджия и Южные Сандвичевы острова' },
  { id: 'OST', label: 'Южная Осетия' },
  { id: 'SSD', label: 'Южный Судан' },
  { id: 'JAM', label: 'Ямайка' },
  { id: 'JPN', label: 'Япония' }
]

export default citizenships

export const getCitizenItem = (citizenId: string): DefaultItem | null =>
  citizenships.find((item) => item.id === citizenId) ?? null
