export enum OrganizationsActionTypes {
  ADD_ORGANIZATION = 'ADD_ORGANIZATION',
  CHANGE_ORGANIZATION = 'CHANGE_ORGANIZATION',
  DELETE_ORGANIZATION = 'DELETE_ORGANIZATION',
  SET_ORGANIZATIONS = 'SET_ORGANIZATIONS'
}
